# Generated by Django 5.2.15 on 2026-06-25 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='customer_name',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(2000)]),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
