# Generated by Django 5.2.15 on 2026-07-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tickets",
            "0002_alter_ticket_customer_name_alter_ticket_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="category",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
